### ISSUE TITLE
Blank home page with Ceph Jewel

### ISSUE THREAD

**Issue by fgal** [A-Dechorgnat/inkscope-lite#3]
Hallo, after one successful installation on Infernalis some time ago, now I just installed latest version of inkscope-lite on admin node in another Ceph cluster, based on Jewel. The home page is essentially blank whereas some difficult plots like pool/OSD mapping do work OK. After some investigation, the home page throws error "Cannot read property up:standby" in file statusApp.js:110 (see attachment).
Is there any missing dependency, may be?

![inkscope_error](https://cloud.githubusercontent.com/assets/7260460/15535591/4f415bd2-226e-11e6-8d28-ec6e3b818af7.png)

For reference, here is the list of ceph packages (I am on CentOS7.2):
ceph-10.2.1-0.el7.x86_64
ceph-base-10.2.1-0.el7.x86_64
ceph-common-10.2.1-0.el7.x86_64
ceph-deploy-1.5.33-0.noarch
ceph-mds-10.2.1-0.el7.x86_64
ceph-mon-10.2.1-0.el7.x86_64
ceph-osd-10.2.1-0.el7.x86_64
ceph-radosgw-10.2.1-0.el7.x86_64
ceph-release-1-1.el7.noarch
ceph-selinux-10.2.1-0.el7.x86_64
libcephfs1-10.2.1-0.el7.x86_64
python-cephfs-10.2.1-0.el7.x86_64

Thanks for your help!

Fulvio

**Comment by A-Dechorgnat** [comment]
Can you download "scripts/statusApp.js" and validate the fix (for the Home page issue) ?

**Comment by fgal** [comment]
Works perfectly, thanks a lot for your prompt action!

Fulvio

**Comment by solune** [comment]
Hi,
I have the same problem with inkscope (not light ! ) and jewel. Can you push the modified statusApp.js on the other side ?
Thanks

**Comment by A-Dechorgnat** [comment]
Sorry, I forgot to push the fix. That's done on https://github.com/inkscope/inkscope/commit/94871503f07bb17d5b2a07023f90f7f94cbb42b0
I also forgot to push mdsApp.js. Done in https://github.com/inkscope/inkscope/commit/cba0a7ead98b9f8b210430d3eeb77b16c5f0d259
